# Site settings
title: Yidi Shui
email: shuiyidi@sjtu.edu.cn
description: > # this means to ignore newlines until "baseurl:"
   I'm a Mphil student in the School of Ocean & Civil Engineering at Shanghai Jiao Tong University.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://shuiyidi.github.io" # the base hostname & protocol for your site
production_url: "https://shuiyidi.github.io"
github_username: shuiyidi
permalink: /blog/:year/:month/:title.html

twitter:
  username: shuiyidi

sass:
  style: compressed

collections:
  publications:
    output: false

jekyll-mentions:
  base_url: https://twitter.com

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-mentions
